### ISSUE TITLE
items = (item['media'],) if isinstance(item['media'], dict) else item['media']

### ISSUE THREAD

**Issue by SalahAdDin** [ramusus/django_utils#1]
What function haves this piece of code?

```
if 'media' not in item:
            return True

        items = (item['media'],) if isinstance(item['media'], dict) else item['media']

        if len(items) > 1:
            handler.startElement(u"media:group", {})

        for item in items:
```

Don't works for me, and if i deletes this code, i can see all media content, but, with this code i can't see media content.

I can't find 'media' attribute from any side, have 'media:title' and others, but don't these; in adittion, if you delete the first condition, fails django server, then, we can think that the first condition ever return True, why?

I'm very confussed.

**Comment by ramusus** [comment]
This code is just copypaste of snippet http://www.djangosnippets.org/snippets/1648/
Perhaps it's very old code and may be it's necessary to refactor it. I don't understand exactly what the problem you are facing to. May be you can find answer here http://www.djangosnippets.org/snippets/1648/?
